global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Внутренний порт остается 9090
    scrape_interval: 30s
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Внутренний порт остается 9100
    scrape_interval: 30s
    
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Внутренний порт остается 3000
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
