groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 90% for more than 2 minutes. Current value: {{ $value }}%"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High Memory usage detected"
          description: "Memory usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"

      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 90
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High Disk usage detected"
          description: "Disk usage is above 90% for more than 5 minutes. Current value: {{ $value }}%"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"

      - alert: HighSystemLoad
        expr: node_load1 > 4
        for: 3m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High system load detected"
          description: "System load is above 4 for more than 3 minutes. Current value: {{ $value }}"
